enum {
  UPG_Generic_Desktop = 0x01,
  UPG_Simulation_Controls,
  UPG_VR_Controls,
  UPG_Sports_Controls,
  UPG_Gaming_Controls,
  UPG_Keyboard = 0x07,
  UPG_LEDs,
  UPG_Button,
  UPG_Ordinals,
  UPG_Telephony_Devices,
  UPG_Consumer_Devices,
  UPG_Digitizers,
  UPG_Unicode,
  UPG_Alphanumeric_Display = 20,
  UPG_Monitor = 128,
  UPG_VESA_Virtual_Controls,
  UPG_VESA_Command,
  UPG_Power_Device,
  UPG_Battery_System,
};
