// https://www.usb.org/sites/default/files/hut1_4.pdf



enum report {
  UsagePage = 0x05,
  Usage = 0x09,
  Collection = 0xA1,
  UsageMinimum = 0x19,
  UsageMaximum = 0x29,
  LogicalMinimum = 0x15,
  LogicalMaximum = 0x25,
  ReportCount = 0x95,
  ReportSize = 0x75,
  Input = 0x81,
  EndCollection = 0xC0,
};

enum UsagePages {
  GenericDesktop = 0x01,
  SimulationControls,
  VRControls,
  SportControls,
  GameControls,
  GenericDeviceControls,
  Keyboard,
  LED,
  Button,
  Ordinal,
  Telephony,
  Consumer,
  Digitizers,
  Haptics,
  PhysicalInputDevice,
  Unicode,
  SoC,
  EyeAndHeadTrackers,
  // 0x13 reserved
  AuxiliaryDisplay = 0x14,
  // 0x15 - 0x1F reserved
  Sensors = 0x20,
  // 0x21 - 0x3F reserved
  MedicalInstrument = 0x40,
  BrailleDisplay,
  // 0x42 - 0x58 reserved
  LightingAndIllumination = 0x59,
  // 0x5A - 0x7F reserved
  Monitor = 0x80,
  MonitorEnumerated,
  VESAVirtualControls,
  // 0x83 reserved
  Power = 0x84,
  BatterySystem,
  // 0x86 - 0x8B reserved
  BarcodeScanner = 0x8C,
  Scales,
  MagneticStripeReader,
  // 0x8F reserved
  CameraControl = 0x90,
  Arcade,
  GamingDevice,
  // 0x93 - F1CF reserved
  FIDOAlliance = 0xF1D0,
  // F1D1 - FEFF reserved
  // FF00 - FFFF Vendor-defined
};

enum GenericDesktopUsages {
  Pointer = 0x01,
  Mouse,
  // 0x03 reserved
  Joystick = 0x04,
  Gamepad,
  Keyboard,
  Keypad,
  MultiaxisController,
  TabletPCSystemControls,
  WaterCoolingDevice,
  ComputerChassisDevice,
  WirelessRadioControls,
  PortableDeviceControl,
  SystemMultiaxisController,
  SpatialController,
  AssistiveControl,
  DeviceDock,
  DockableDevice,
  CallStateManagementControl,
  // 0x14 - 0x2F reserved
  X = 0x30,
  Y,
  Z,
  Rx,
  Ry,
  Rz,
  Slider,
  Dial,
  Wheel,
  HatSwitch,
  CountedBuffer,
  ByteCount,
  MotionWakeup,
  Start,
  Select,
  // 0x3F reserved
  Vx = 0x40,
  Vy,
  Vz,
  Vbrx,
  Vbry,
  Vbrz,
  Vno,
  FeatureNotification,
  ResolutionMultiplier,
  Qx,
  Qy,
  Qz,
  Qw,
  // 0x4D - 0x7F reserved
  SystemControl,
  SystemPowerDown,
  SystemSleep,
  SystemWakeUp,
  SystemContextMenu,
  SystemMainMenu,
  SystemAppMenu,
  SystemMenuHelp,
  SystemMenuExit,
  SystemMenuSelect,
  SystemMenuRight,
  SystemMenuLeft,
  SystemMenuUp,
  SystemMenuDown,
  SystemColdRestart,
  SystemWarmRestart,
  DpadUp,
  DpadDown,
  DpadRight,
  DpadLeft,
  IndexTrigger,
  PalmTrigger,
  Thumstick,
  SystemFunctionShift,
  SystemFunctionShiftLock,
  SystemFunctionShiftLockIndicator,
  SystemDismissNotification,
  SystemDoNotDisturb,
  // 0x9C - 0x9F reserved
  SystemDock = 0xA0,
  SystemUndock,
  SystemSetup,
  SystemBreak,
  SystemDebuggerBreak,
  
};
